### ISSUE TITLE
Naming: use descriptive name

### ISSUE THREAD

**Issue by dafeilei** [therunnersfbu/team_project#20]
https://github.com/therunnersfbu/team_project/blob/f1ede777bf83977b5989d1616dfdc4de2e0151f8/app/src/main/java/com/example/team_project/CardViewAdapter.java#L13

**Comment by szambri** [comment]
Renamed to HorizontalScrollAdapter, to indicate that this adapter is used in all instances of horizontal scrolling (tags and suggestions items)
