### ISSUE TITLE
Simplify code

### ISSUE THREAD

**Issue by dafeilei** [therunnersfbu/team_project#27]
View itemView = LayoutInflater.from(parent.getContext()).inflate(isTag? R.layout.item_tag : R.layout.item_suggestion, parent, false);
return new ViewHolder(itemView);

https://github.com/therunnersfbu/team_project/blob/f1ede777bf83977b5989d1616dfdc4de2e0151f8/app/src/main/java/com/example/team_project/CardViewAdapter.java#L39

**Comment by szambri** [comment]
this is great thank you!
