### ISSUE TITLE
You only need to call fetchIfNeededInBackground when addedEvents is null, right?

### ISSUE THREAD

**Issue by dafeilei** [therunnersfbu/team_project#53]
https://github.com/therunnersfbu/team_project/blob/f2f550b4e11c8c0de781f6501c48f1f86d292c09/app/src/main/java/com/example/team_project/calendar/MyCalendarFragment.java#L82

**Comment by shannonmj** [comment]
We must call fetchIfNeededInBackground anytime the data is changed or events are added or deleted. This makes sure that the parse objects are retrieved and the calendar displays up-to-date information
