### ISSUE TITLE
instead of fetching all events and filter by date, can you just fetch all events with given date?

### ISSUE THREAD

**Issue by dafeilei** [therunnersfbu/team_project#54]
https://github.com/therunnersfbu/team_project/blob/f2f550b4e11c8c0de781f6501c48f1f86d292c09/app/src/main/java/com/example/team_project/calendar/MyCalendarFragment.java#L155

**Comment by shannonmj** [comment]
Yup! I used a filter function that looks for the dateClicked and creates a new list
