### ISSUE TITLE
You don't need mEpochTime, right?

### ISSUE THREAD

**Issue by dafeilei** [therunnersfbu/team_project#55]
https://github.com/therunnersfbu/team_project/blob/f2f550b4e11c8c0de781f6501c48f1f86d292c09/app/src/main/java/com/example/team_project/calendar/MyCalendarFragment.java#L151

**Comment by shannonmj** [comment]
I need the mEpochTime in order to place the spots on the calendar because this is the way the format the repository takes day and time.
