### ISSUE TITLE
Can you add logic to only show the toast once?

### ISSUE THREAD

**Issue by dafeilei** [therunnersfbu/team_project#56]
https://github.com/therunnersfbu/team_project/blob/f2f550b4e11c8c0de781f6501c48f1f86d292c09/app/src/main/java/com/example/team_project/calendar/MyCalendarFragment.java#L103

**Comment by shannonmj** [comment]
I just changed it! I was able to do this by adding a showToast column in the User's parse data that is initially true and after that is false and stops the toast from showing to the user again.
